#!/bin/bash
echo "compiling static binary using jrei/crystal-alpine dockerimage..."
docker run --rm -it -v $PWD:/app -w /app jrei/crystal-alpine crystal build src/dynamic_memory_error.cr --static --release --no-debug || exit 1
cp dynamic_memory_error payload # cp since dynamic_memory_error belongs to root because docker is annoying
echo "compilation done."
echo ""
echo "deploying as a google cloud function named 'crystal-dynamic-memory-test'..."
echo ""
gcloud beta functions deploy crystal-dynamic-memory-test --source=. --entry-point=init --memory=2048MB --timeout=540 --trigger-http || exit 1
echo "deploy done."
echo "please curl the deploy url shown above to run the cloud function (httpsTrigger)"
